version: '3.9'
name: evidencija_zaposlenih
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    image: evidencija_zaposlenih_image:latest
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s  # Optional: delay before restarting the container
    healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
       interval: 30s
       timeout: 5s
       retries: 2  # Limit the number of health check retries
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fakultet_projekat
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: fakultet_projekat
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./init/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
