/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package rs.ac.bg.fon.njt.webapp.domain;

import rs.ac.bg.fon.njt.webapp.domain.enums.Role;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import java.util.Collection;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import rs.ac.bg.fon.njt.webapp.validator.MyRoleValidator;

/**
 * Entity class representing a user. This class is mapped to the '_user' table
 * in the database and implements {@link UserDetails} for Spring Security.
 *
 * @see jakarta.persistence.Entity
 * @see jakarta.persistence.Table
 * @see org.springframework.security.core.userdetails.UserDetails
 *
 * @author aleks
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "_user")
public class User implements UserDetails {

    /**
     * The unique identifier for the user. It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * The first name of the user. Must contain between 3 and 30 characters.
     * Must start with a capital letter and contain only letters.
     */
    @NotBlank(message = "Firstname is mandatory")
    @Size(min = 3, max = 30, message = "Firstname must contain between 3 and 30 characters")
    @Pattern(regexp = "^[A-Z][a-z]+$",
            message = "Name must start with capital letter and contain only letters. Other letters must be lowercase.")
    private String firstname;
    /**
     * The last name of the user. Must contain between 3 and 30 characters. Must
     * start with a capital letter and contain only letters.
     */
    @NotBlank(message = "Lastname is mandatory")
    @Size(min = 3, max = 30, message = "Lastname must contain between 3 and 30 characters")
    @Pattern(regexp = "^[A-Z][a-z]+$",
            message = "Lastname must start with capital letter and contain only letters. Other letters must be lowercase.")
    private String lastname;
    /**
     * The username of the user. It is a mandatory field.
     */
    @NotBlank(message = "Username is mandatory")
    private String username;
    /**
     * The email address of the user. Must be a valid email address format.
     */
    @NotBlank(message = "Email is mandatory")
    @Email(regexp = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$",
            message = "Please provide valid email adress")
    private String email;
    /**
     * The password of the user. It is a mandatory field.
     */
    @NotBlank(message = "Password is mandatory")
    private String password;
    /**
     * The role of the user. Must be validated by a custom role validator.
     */
    @Enumerated(EnumType.STRING)
    @NotNull(message = "Role is mandatory")
    @MyRoleValidator
    private Role role;

    /**
     * Constructs a new User with the specified details.
     *
     * @param firstname the first name of the user
     * @param lastname the last name of the user
     * @param username the username of the user
     * @param email the email address of the user
     * @param password the password of the user
     * @param role the role of the user
     */
    public User(String firstname, String lastname, String username, String email, String password, Role role) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.username = username;
        this.email = email;
        this.password = password;
        this.role = role;
    }

    /**
     * Returns the authorities granted to the user. In this case, a single
     * authority based on the user's role.
     *
     * @return a collection of granted authorities
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return List.of(new SimpleGrantedAuthority(role.name()));
    }

    /**
     * Indicates whether the user's account has expired.
     *
     * @return true, as the account is always non-expired
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * Indicates whether the user is locked or unlocked.
     *
     * @return true, as the account is always non-locked
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * Indicates whether the user's credentials (password) has expired.
     *
     * @return true, as the credentials are always non-expired
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * Indicates whether the user is enabled or disabled.
     *
     * @return true, as the user is always enabled
     */
    @Override
    public boolean isEnabled() {
        return true;
    }

}
